### ISSUE TITLE
Can't leave rating for finished art

### ISSUE THREAD

**Issue by tigrrlily** [Csardelacal/YCH-Issues#55]
Platform: mobile
 Operating system: Android
 Browser: Firefox, Chrome
 URL: https://ych.commishes.com/followUp/submit/Q6U6/ with token
 
 What were you trying to do: leave a rating for an artist after she finished a picture
 
 What was supposed to happen: I was supposed to be able to leave the rating 
 
 What happened: I got the following error message

![Screenshot_20210328-104238_1](https://user-images.githubusercontent.com/68269257/112759957-8730b900-8fb2-11eb-9d46-048973aba8d0.jpg)

**Comment by tigrrlily** [comment]
Hi, I see you've closed this issue but I tried again and I'm still getting the same error. Is there something I'm doing wrong here? Could the link for this review be regenerated perhaps, or is there another way I could leave it?

**Comment by Csardelacal** [comment]
Hey there @tigrrlily ,

I have actually been reviewing the issue, and just closed it because I didn't expect to get some follow-up. My guess would be that the interface warns that the character limit for a review is 500 characters, but the actual limit that loot enforces is 400. Do you have the review text you were trying to post?

Also, thanks for letting me know that you're still interested in this issue.

**Comment by tigrrlily** [comment]
Oh! Ok, I see. I think that must've been in, because it was ~470 characters before and wouldn't work, but I just now trimmed it down under 400 and it went through! 😊 Is the interface locked in at the 500 character limit or can that be changed to prevent that from happening in future?
